apiVersion: v1
kind: Secret
metadata:
  name: chunkmydocs-secrets
  namespace: chunkmydocs
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://postgres:password@postgres-service.chunkmydocs.svc.cluster.local:5432/chunkmydocs'
  PG__URL: 'postgresql://postgres:password@postgres-service.chunkmydocs.svc.cluster.local:5432/chunkmydocs'
  PG__POOL__MAX_SIZE: '5'
  RRQ__URL: 'http://rrq-service.chunkmydocs.svc.cluster.local'
  EXTRACTION__VERSION: '1.1.0'
  EXTRACTION__EXTRACTION_QUEUE_FAST: 'chunkr-fast'
  EXTRACTION__EXTRACTION_QUEUE_HIGH_QUALITY: 'chunkr-high-quality'
  EXTRACTION__PDLA_FAST_URL: 'http://pdla-service.chunkmydocs.svc.cluster.local'
  EXTRACTION__PDLA_URL: 'http://pdla-service.chunkmydocs.svc.cluster.local'
  EXTRACTION__TASK_EXPIRATION:
  EXTRACTION__S3_BUCKET: 'lumina-user-ingestion'
  EXTRACTION__BATCH_SIZE: '10'
  EXTRACTION__BASE_URL: 'http://api.chunkmydocs.com/api'
  AWS__ENDPOINT: 'http://127.0.0.1:9000'
  AWS__ACCESS_KEY: 'accesskey'
  AWS__SECRET_KEY: 'secretkey'
  AWS__REGION: 'foo'
  AUTH__KEYCLOAK_URL: 
  AUTH__KEYCLOAK_REALM: 
  MAX_TOTAL_LIMIT: '1073741824'
  MAX_MEMORY_LIMIT: '1073741824'
  TASK__SERVICE_URL: 'http://task-service.chunkmydocs.svc.cluster.local'
  TASK__PAGE_IMAGE_DENSITY: '150'
  TASK__PAGE_IMAGE_EXTENSION: '.jpg'
  TASK__SEGMENT_IMAGE_EXTENSION: '.jpg'
  TASK__SEGMENT_IMAGE_QUALITY: '100'
  TASK__SEGMENT_IMAGE_RESIZE:
  TASK__SEGMENT_BBOX_OFFSET: '5'