apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  namespace: chunkmydocs
  labels:
    app.kubernetes.io/name: task
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: task
  template:
    metadata:
      namespace: chunkmydocs
      labels:
        app.kubernetes.io/name: task
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - task
              topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "nvidia.com/gpu.b"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: task
        image: luminainc/task:5c3b0e11
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: chunkmydocs-secrets
        ports:
        - containerPort: 3000
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 5Gi